kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: test
subjects:
  - kind: Group
    name: system:serviceaccounts
roleRef:
  kind: ClusterRole
  name: test
  apiVersion: rbac.authorization.k8s.io/v1alpha1
