kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  namespace: default
  name: admin
  apiVersion: rbac.authorization.k8s.io/v1alpha1
